// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/gameklinedata.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	model "echoes-api/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockGameKlineDataRepository is a mock of GameKlineDataRepository interface.
type MockGameKlineDataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGameKlineDataRepositoryMockRecorder
}

// MockGameKlineDataRepositoryMockRecorder is the mock recorder for MockGameKlineDataRepository.
type MockGameKlineDataRepositoryMockRecorder struct {
	mock *MockGameKlineDataRepository
}

// NewMockGameKlineDataRepository creates a new mock instance.
func NewMockGameKlineDataRepository(ctrl *gomock.Controller) *MockGameKlineDataRepository {
	mock := &MockGameKlineDataRepository{ctrl: ctrl}
	mock.recorder = &MockGameKlineDataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameKlineDataRepository) EXPECT() *MockGameKlineDataRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGameKlineDataRepository) Create(ctx context.Context, data *model.GameKlineDatum) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGameKlineDataRepositoryMockRecorder) Create(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGameKlineDataRepository)(nil).Create), ctx, data)
}

// CreateBatch mocks base method.
func (m *MockGameKlineDataRepository) CreateBatch(ctx context.Context, data []*model.GameKlineDatum) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockGameKlineDataRepositoryMockRecorder) CreateBatch(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockGameKlineDataRepository)(nil).CreateBatch), ctx, data)
}

// GetByDealRecordID mocks base method.
func (m *MockGameKlineDataRepository) GetByDealRecordID(ctx context.Context, dealRecordID int64) ([]*model.GameKlineDatum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDealRecordID", ctx, dealRecordID)
	ret0, _ := ret[0].([]*model.GameKlineDatum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDealRecordID indicates an expected call of GetByDealRecordID.
func (mr *MockGameKlineDataRepositoryMockRecorder) GetByDealRecordID(ctx, dealRecordID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDealRecordID", reflect.TypeOf((*MockGameKlineDataRepository)(nil).GetByDealRecordID), ctx, dealRecordID)
}
