// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"echoes-api/internal/handler"
	"echoes-api/internal/job"
	"echoes-api/internal/repository"
	"echoes-api/internal/router"
	"echoes-api/internal/server"
	"echoes-api/internal/service"
	"echoes-api/pkg/app"
	"echoes-api/pkg/jwt"
	"echoes-api/pkg/log"
	"echoes-api/pkg/server/http"
	"echoes-api/pkg/sid"
	"echoes-api/pkg/wechat"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(viperViper)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(viperViper, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	wechatWechat := wechat.NewWechat(viperViper)
	wechatHandler := handler.NewWechatHandler(handlerHandler, wechatWechat)
	deps := router.Deps{
		Logger:        logger,
		Config:        viperViper,
		JWT:           jwtJWT,
		UserHandler:   userHandler,
		WechatHandler: wechatHandler,
	}
	httpServer := server.NewHTTPServer(deps)
	jobJob := job.NewJob(transaction, logger, sidSid)
	userJob := job.NewUserJob(jobJob, userRepository)
	jobServer := server.NewJobServer(logger, userJob)
	appApp := newApp(httpServer, jobServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewWechatHandler)

var jobSet = wire.NewSet(job.NewJob, job.NewUserJob)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer)

// build App
func newApp(
	httpServer *http.Server,
	jobServer *server.JobServer,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, jobServer), app.WithName("auto-go-server"))
}
